### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by itowhid06** [alessandrotesoro/vuewp#1]
This is not a typical github issue, but it would great to have a documentation about how to integrate the toolkit with wordpress and use the components. BTW, any plan to publish this as npm package?

**Comment by alessandrotesoro** [comment]
I haven't had the time yet to publish a documentation because I've been using it internally for a project of mine. It's already published as an npm package here https://www.npmjs.com/package/@alessandrotesoro/vuewp
